name: Go

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: ./build.sh

    - name: Archive Windows artifacts
      uses: actions/upload-artifact@v2
      with:
        path: adalanche-windows-*

    - name: Archive Linux artifacts
      uses: actions/upload-artifact@v2
      with:
        path: adalanche-linux-*

    - name: Archive OSX artifacts
      uses: actions/upload-artifact@v2
      with:
        path: adalanche-osx-*
